### ISSUE TITLE
Erreur dans les logs avec SimplePie

### ISSUE THREAD

**Issue by Tetsumaki** [ldleman/Leed#326]
Je ne sais pas si c'est depuis la mise à jour depuis la branche NewSimplePie mais j'ai 3 erreurs comme ça dans les logs :
```text
[Sat Feb 22 12:37:52 2014] [error] [client 82.*******] PHP Warning:  DOMDocument::loadXML(): Premature end of data in tag feed line 2 in Entity, line: 2 in /srv/http/***/leed/SimplePie.class.php on line 4772, referer: https://tetsumaki.net/***/leed/index.php
```

**Comment by Simounet** [comment]
Je n'ai eu aucune erreur de ce style dans mes logs depuis un bail. J'ai testé aujourd'hui-même avec le RSS d'ariase et sans soucis non plus. Je ferme.
