### ISSUE TITLE
Synchronisation manuelle avec Nginx > pas d'état d'avancement

### ISSUE THREAD

**Issue by Tetsumaki** [ldleman/Leed#340]
Hé ho.

Je viens de migrer de Apache2 à Nginx et Leed fonctionne très bien mais lorsqu'on fait une synchronisation manuelle, au lieu d'avoir la progression qui défile des flux actualisés en temps réel, on ne voit rien.
Obligé d'attendre que tout sois actualisé pour tout voir s'afficher d'un seul bloc.

Une idée ?
Je ne sais pas si ça vient de votre javascript ou de nginx.

Ce n'est pas trop gênant mais bon, l'abandon de l'iframe est prévu ou pas ?

**Comment by Sbgodin** [comment]
Femme faute d'activité. Rouvrir si besoin.
