### ISSUE TITLE
Ajouter un lien ou picto suppression flux dans le log

### ISSUE THREAD

**Issue by fran6t** [ldleman/Leed#345]
Lorsque l'on a beaucoup de flux et qu'un flux est en erreur il faut actuellement faire la démarche suivante : Cliquer sur le flux en question pour constater ce qui se passe et si l'on constate que le flux n'est plus bon (domaine disparu, flux abandonné) il faut alors retrouver ce flux parmis toute sa liste de flux pour le supprimer. Je verrais donc bien une des deux solutions 
La premiere  l'ajout d'un lien supprimer
La seconde qui serait mieux une ancre nommée permettant de rappeler la page de gestion en étant a peu pret positionné à l'endroit du flux cela permettrai alors soit de modifier ou supprimer.
Je veux bien tenter de l'implémenter, mais je ne suis pas à l'aise à Github si quelqu'un veut bien me parrainer un peu vous pouvez compter sur moi.

**Comment by Sbgodin** [comment]
Quelqu'un voit-il un intérêt pour cette fonctionnalité ?

Résumé : il s'agit de pouvoir accéder d'un clic à la page de gestion des flux, en cliquant sur la ligne concernant le flux pendant la synchronisation.

Me concernant, je vais de toutes façons dans la gestion des flux. Ceux en erreur sont en rouge. Donc, bon...

**Comment by Simounet** [comment]
Je n'utilise jamais la synchro via le front donc j'avoue ne pas être intéressé. Après, la modification peut être mineure donc je propose une pull request de la part de @fran6t (si tu es toujours dans les parages). Fermeture de l'issue en attendant ?

**Comment by Sbgodin** [comment]
A voté !

**Comment by fran6t** [comment]
Pas de soucis pour cette fermeture, perso je ne regarde plus non plus via le front trop de flux.

**Comment by Simounet** [comment]
Super, ta confirmation conforte cette fermeture. Merci de ton passage et bonne journée.
