### ISSUE TITLE
Fonction amélioration ou nouvelle

### ISSUE THREAD

**Issue by fran6t** [ldleman/Leed#356]
Comme conseillé voici une issue qui n'en est pas une (cf conseil de @cobalt74). En fait pour un theme façon Google Flux ou Google Current j'ai maintenant besoins de quelques fonctions. 
Je fais donc appel à votre expérience plutôt que de réinventer la roue. Voici sans préparation quelques fonctions que je souhaite...
Fonction TruncateChapeau
J'ai vu qu'il y a déjà en natif une fonction truncate, mais voilà il me la faudrait plus performante dans le sens ou il me faudrait une truncate qui avant aurait virer les balises car faire un truncate qui tombe au milieu d'une img src image c'est pas top en plus ce truncate faudrait idéalement qu'il coupe après un mot
Function FindImageRepresent
Trouve les images dans le flux et me fait remonter la plus grosse en taille ainsi que ses dimensions (afin de permettre de virer les pictos style FB Tweeter) l'idée serait donc de trouver la plus grosse elle devrait être ainsi representative le plus souvent du sujet du billet.
Ce sont les deux principales qui me viennent, la premiere il faut que je refouille dans mes vieux dev j'ai peut-être ça quelques part mais si quelqu'un l'a sous la main car l'utilisant beaucoup ou dans un dev recent je suis preneur.
Sinon le thème avance bien, beaucoup de boulot encore il sera responsive et concernera que la consultation de dossier et flux pas de gestion, l'idée étant de la consultation façon magazine (feuilletage ballade) uniquement.

**Comment by Sbgodin** [comment]
Rouvrir si quelqu'un veut poursuivre le développement.
