### ISSUE TITLE
ergo marigolds

### ISSUE THREAD

**Issue by tmos** [ldleman/Leed#387]
Un petit point qui pourrait être amélioré selon moi : 
sur l'image suivante on ne différencie pas les boutons et les «notices» d'installation. Les deux sont des blocs oranges, et instinctivement on passe la souris dessus pour voir quoi y faire.
D'ailleurs je ne pourrais que vous conseiller de faire prendre un peu de gras à vos boutons, mais ça c'est une autre histoire :)
![ergo](https://cloud.githubusercontent.com/assets/1592709/2855048/17801d96-d158-11e3-9317-a062b325410b.png)

**Comment by Sbgodin** [comment]
Fermé faute de développement. Rouvrir au besoin.

**Comment by Simounet** [comment]
Il a raison et je prends cette issue.

**Comment by Sbgodin** [comment]
Ça roule.

**Comment by Simounet** [comment]
Gestion des couleurs sur les informations pour être plus clair. Seuls ceux en orange sont des boutons.

**Comment by Sbgodin** [comment]
N'oublie pas de fusionner dans Idle/leed !

**Comment by Simounet** [comment]
C'est déjà dans la branche dev de ce repo via la PR mergée tout à l'heure. 😛
