### ISSUE TITLE
Nettoyage et optimisations pour lutter contre les ralentissements

### ISSUE THREAD

**Issue by kvnco** [ldleman/Leed#393]
Bonjour,

J'utilise Leed v1.6.1 Stable de façon assez intensive : 435 flux, et Leed_event fait 135 Mo pour 19300 tuples.
Tout ceci est installé sur un « petit » Dockstar (http://archlinuxarm.org/platforms/armv5/seagate-dockstar).

Ce qui fait qu'avec le temps j'observe des performances de moins en moins bonnes (chargement de 25 éléments dépassant souvent 45 s.).

Je suis donc curieux de savoir s'il y a des requêtes de nettoyage (pour supprimer d'anciens posts lus, ou autre) ou d'optimisation (des index ?) que je pourrais passer sur la base.

J'ai dernièrement configuré le nombre de posts conservés à 50, pourtant en base j'ai encore des flux pour lesquels le nombre de posts lus est supérieur. À quel moment est donc appliqué ce nettoyage ?

Je précise par ailleurs que la synchro ne se fait que toutes les 6h. Ce n'est donc pas elle qui est à l'origine de mes ralentissements.

Merci pour vos retours !

Kevin

**Comment by Tabrisange** [comment]
Voici mes stats pour information après quelques années d'utilisation sans supprimer aucun event:

Synchronisation terminée.

    4 erreur(s)
    206 bon(s)
    210 au total
    145.232 secondes
    27 nouveaux articles 

=> 201 flux

mysql> select count(*) from leed_event;
+----------+
| count(*) |
+----------+
|   359104 |
+----------+
1 row in set (0,09 sec)

mysql> SELECT table_schema "Data Base Name",  table_name,   sum( data_length + index_length ) / 1024 / 1024 "table_size Size in MB",     sum( data_free )/ 1024 / 1024 "Free Space in MB" FROM information_schema.TABLES where table_schema = 'leed' GROUP BY table_schema,table_name order by 3 ;
+----------------+-------------------------+-----------------------+------------------+
| Data Base Name | table_name              | table_size Size in MB | Free Space in MB |
+----------------+-------------------------+-----------------------+------------------+
| leed           | leed_folder             |            0.01562500 |       0.00000000 |
| leed           | leed_user               |            0.01562500 |       0.00000000 |
| leed           | leed_plugin_feaditlater |            0.01562500 |       0.00000000 |
| leed           | leed_configuration      |            0.01562500 |       0.00000000 |
| leed           | leed_feed               |            0.15625000 |       0.00000000 |
| leed           | leed_event              |         1665.18750000 |       0.00000000 |
+----------------+-------------------------+-----------------------+------------------+
6 rows in set (0,01 sec)


=> 359 104 lignes dans la table leed_event
=> Taille de la table 1665 MO

index que j'ai du créer : 

  KEY `dba_idx_leed_event_1` (`guid`(20),`feed`),
  KEY `dba_idx_leed_event_2` (`feed`,`guid`(20)),
  KEY `dba_idx_leed_event_3` (`feed`,`unread`)

Sinon ça va, ça marche pas trop mal vu que sur les 10 derniers jours j'ai une bonne moyenne de mise à jour 

mysql> select DATE_FORMAT(from_unixtime(pubdate), '%Y-%m-%d'), count(*) from leed_event group by DATE_FORMAT(from_unixtime(pubdate), '%Y-%m-%d') order by 1 desc;
+-------------------------------------------------+----------+
| DATE_FORMAT(from_unixtime(pubdate), '%Y-%m-%d') | count(*) |
+-------------------------------------------------+----------+
| 2016-05-30                                      |      661 |
| 2016-05-29                                      |      477 |
| 2016-05-28                                      |      517 |
| 2016-05-27                                      |      648 |
| 2016-05-26                                      |      650 |
| 2016-05-25                                      |      699 |
| 2016-05-24                                      |      690 |
| 2016-05-23                                      |      657 |
| 2016-05-22                                      |      478 |
| 2016-05-21                                      |      496 |
| 2016-05-20                                      |      699 |

**Comment by Simounet** [comment]
Joli score ! Je ne pourrai pas faire de comparaison vu que je ne garde pas les vieux articles lus mais content de voir que ça tourne bien chez toi.

**Comment by kraoc** [comment]
Synchronisation terminée.
```
0 erreur(s)
68 bon(s)
68 au total
18.947 secondes
0 nouveaux articles
```
count(*) -> 1691

Le reste je n'arrive pas à passer la commande via PhpMyAdmin

**Comment by Tabrisange** [comment]
Petite maj pour les perfs : 

mysql> select count(*) from leed_event;
+----------+
| count(*) |
+----------+
|   439377 |
+----------+
1 row in set (0,45 sec)

mysql> SELECT table_schema "Data Base Name", table_name, sum( data_length + index_length ) / 1024 / 1024 "table_size Size in MB", sum( data_free )/ 1024 / 1024 "Free Space in MB" FROM information_schema.TABLES where table_schema = 'leed' GROUP BY table_schema,table_name order by 3 ;
+----------------+-------------------------+-----------------------+------------------+
| Data Base Name | table_name              | table_size Size in MB | Free Space in MB |
+----------------+-------------------------+-----------------------+------------------+
| leed           | leed_configuration      |            0.01562500 |       0.00000000 |
| leed           | leed_folder             |            0.01562500 |       0.00000000 |
| leed           | leed_user               |            0.01562500 |       0.00000000 |
| leed           | leed_plugin_feaditlater |            0.01562500 |       0.00000000 |
| leed           | leed_feed               |            0.14062500 |       0.00000000 |
| leed           | leed_event              |         2047.17187500 |       5.00000000 |
+----------------+-------------------------+-----------------------+------------------+
6 rows in set (0,03 sec)


j'approche des 500 000 items dans la table leed_event qui elle fait 2go

Lors de la synchronisation : 

Synchronisation terminée.

    1 erreur(s)
    214 bon(s)
    215 au total
    138.800 secondes
    30 nouveaux articles 

Et le cron tourne toutes les 30 minutes

J'aimerais bien avoir un détail du temps de synchro de chaque flux plutôt que le temps global

**Comment by Simounet** [comment]
Wahou ! C'est un vrai archivage que tu nous fais là. Par contre, tu devrais avoir le détail des temps de synchro dans tes logs. Es-tu sûre qu'il n'est pas tronqué ?

**Comment by Tabrisange** [comment]
My bad, j'étais fatiguée.

Petite info, index à créer :

create index dba_idx_leed_event_5 on leed_event(guid(60),feed);

Les requêtes de vérification d'existence des évènement sont plus rapides :

AVANT
mysql> explain SELECT * FROM `leed_event`  WHERE `guid`="http://9gag.com/gag/aW8L7YK" AND `feed`="216" LIMIT 1;
+----+-------------+------------+------------+------+--------------------------------------------------------------------------+-----------+---------+-------+--------+----------+-------------+
| id | select_type | table      | partitions | type | possible_keys                                                            | key       | key_len | ref   | rows   | filtered | Extra       |
+----+-------------+------------+------------+------+--------------------------------------------------------------------------+-----------+---------+-------+--------+----------+-------------+
|  1 | SIMPLE      | leed_event | NULL       | ref  | indexfeed,dba_idx_leed_event_1,dba_idx_leed_event_2,dba_idx_leed_event_3 | indexfeed | 4       | const | 202284 |    10.00 | Using where |
+----+-------------+------------+------------+------+--------------------------------------------------------------------------+-----------+---------+-------+--------+----------+-------------+
1 row in set, 1 warning (0,03 sec)

APRES

mysql> explain SELECT * FROM `leed_event`  WHERE `guid`="http://9gag.com/gag/aW8L7YK" AND `feed`="216" LIMIT 1;
+----+-------------+------------+------------+------+-----------------------------------------------------------------------------------------------+----------------------+---------+-------------+------+----------+-------------+
| id | select_type | table      | partitions | type | possible_keys                                                                                 | key                  | key_len | ref         | rows | filtered | Extra       |
+----+-------------+------------+------------+------+-----------------------------------------------------------------------------------------------+----------------------+---------+-------------+------+----------+-------------+
|  1 | SIMPLE      | leed_event | NULL       | ref  | indexfeed,dba_idx_leed_event_1,dba_idx_leed_event_2,dba_idx_leed_event_3,dba_idx_leed_event_5 | dba_idx_leed_event_5 | 246     | const,const |    1 |   100.00 | Using where |
+----+-------------+------------+------------+------+-----------------------------------------------------------------------------------------------+----------------------+---------+-------------+------+----------+-------------+
1 row in set, 1 warning (0,00 sec)

**Comment by Tabrisange** [comment]
Avant index:

Synchronisation terminée.

    2 erreur(s)
    214 bon(s)
    216 au total
    210.431 secondes
    41 nouveaux articles 

Après index et optimize table

Synchronisation terminée.

    2 erreur(s)
    214 bon(s)
    216 au total
    48.400 secondes
    25 nouveaux articles

**Comment by Simounet** [comment]
Ah oui, ça vaut le coup ! Si tu en as d'autres comme ça, nous sommes preneurs. Je vais voir ça pour l'ajouter vu le gain de perf' obtenu. Merci !

**Comment by Tabrisange** [comment]
ça va surtout être efficace pour les flux ayant beaucoup d'évènements :)

**Comment by Simounet** [comment]
C'est toujours bon à prendre.

**Comment by Sbgodin** [comment]
Par contre, la mise à jour de l'index occasionnera un surcoût. Ce sera probablement mineur, puisque ce sera de l'ajout et les ajouts sont moins fréquents que les lectures.

**Comment by Tabrisange** [comment]
@Sbgodin je te garanti que le gain de performance est largement supérieur par rapport au surcout engendré par la mise à jour de l'index.

**Comment by Sbgodin** [comment]
J'ai préparé la mise à jour de Leed. Reste une question : pourquoi ce nom d'index dba_idx_leed_event_5 ?

**Comment by Tabrisange** [comment]
@Sbgodin heu tu mets le nom que tu veux, c'est juste que suite à des test j'en ai créé 4 avant
et que c'est pour dire index créé par le/la dba sur la table leed_event

En général je préfère les index comme ça ;)

tu peux l'appeler autrement :p

**Comment by Sbgodin** [comment]
Alors, _autrement_ me paraissait un peu trop générique pour le coup ;-) Alors je l'ai nommée _indexguidfeed_ sur le même modèle que les autres index de la table. C'est maintenant sur la dev, cf 3356aa3cf72eaff8642153fb439154e66e44dbfa.
