### ISSUE TITLE
Choix du thème à l'installation

### ISSUE THREAD

**Issue by tmos** [ldleman/Leed#394]
Salut tout le monde !

Une fonction qui pourrait être sympa pour les thèmes alternatifs : proposer le choix du thème à l'installation.

Je sais : vous ne supportez que Marigolds, mais ça pourrait être pratique pour une redistribution ultèrieure (je pense en particulier au package Greeder qu'on aimerai faire, et à l'intégration de Leed à yunoHost [dont je souhaite me charger pendant l'été]).

Quitte, si vous le voulez, à afficher le choix uniquement s'il y à plus d'un thème dans le dossier concerné.

Pour le choix, ça pourrais être sympa d'afficher une miniature (chaque thème insère un thumbs.png de 512px à sa racine par exemple), histoire de rendre le choix plus aisé pour l'utilisateur (choisir sur un nom, c'est un peu con).
Il serait même possible de ré-implémenter cette partie en post-install (au niveau choix du thème dans les options)

Je pense que ça peut être une fonction rendant l’expérience utilisateur plus agréable, et cela permettrait aux utilisateurs d'avoir plus facilement la main sur leur instance, et d'avoir des choix plus aisés et graphiquement plus sympa.

Dites moi ce que vous en pensez :)

**Comment by Sbgodin** [comment]
On peut choisir le thème à l'installation. Je n'ai pas inséré de miniatures, rouvrir si quelqu'un est motivé pour maintenir d'autres thèmes.
