### ISSUE TITLE
Intégration à Yunohost

### ISSUE THREAD

**Issue by tmos** [ldleman/Leed#395]
Salut les contributeurs !

Je ne sais pas si vous connaissez yunohost : https://yunohost.org , c'est une distribution linux dédiée à l'autohébergement (merci @Phyks qui m'a fait découvrir ce projet).

Elle intègre de nombreux logiciels web pré-configurées, type owncloud, roundcube dokuwiki, tinytinyrss, jappix, etc.

Et dans la todo des applis à packager, on trouve notre Leed chéri !
Personne n'étant attribué à l'intégration Leed, je compte m'y mettre cet été (dès le début de mes vacances, d'ici 1mois et demi, 2 mois).

Étant le dev principad de Greeder, je compte bien intégrer mon thème dans le package ! Et si la #394 aboutit, j'espère bien être en mesure de laisser un réel choix à l'utilisateur (pas de mise en avant de Marigolds ou Greeder ou autre). Un peu l'écran de choix de navigateur de windows quoi :D

Bien évidement si d'autres créateurs de thèmes veulent intégrer les leurs, qu'ils me contactent, je me ferais un plaisir d'ajouter leurs travaux au package !

Dites moi ce que vous en pensez, au vu de la notoriété de cette distrib, je pense que ça peut ramener pas mal d'utilisateurs à Leed, et créer une bonne animation.

Quant au boulot d'intégration, je ne suis pas (encore :D) une brute en php, donc je prendrais le temps qu'il me faudra ! Je pense y arriver d'ici la fin de l'été, mais si quelques personnes veulent filer un coup de main, n'hésitez pas à me contacter, je mettrais en place le dépôt d'ici quelques jours.
Comme dit, je serais pleinement disponible d'ici 1mois et demi, 2 mois, mais j'attaquerais petit à petit dès que possible :)

**Comment by Sbgodin** [comment]
Effectivement. C'est exactement ça. Quand on met un htpasswd dans l'instance de Leed et que le nom d'utilisateur utilisé dans le htpasswd correspond à un nom d'utilisateur dans Leed, l'accès est autorisé.
Cela représente un risque ?

@tmos, ça en est où de l'intégration de Leed dans Yunohost ?

**Comment by maniackcrudelis** [comment]
Salut @Sbgodin, Leed est intégré à Yunohost et parfaitement fonctionnel.
Il n'est toutefois pas intégré à la liste des app officielles pour le moment.

Il peut toutefois être installé depuis l'interface de Yunohost en utilisant l'adresse github.
https://github.com/maniackcrudelis/leed_ynh

**Comment by Sbgodin** [comment]
Excellent ^^

Du coup je peux fermer le ticket.
