### ISSUE TITLE
Problème pour trouver la page de téléchargement

### ISSUE THREAD

**Issue by obeet** [ldleman/Leed#397]
Bonjour,
En allant sur http://projet.idleman.fr/leed/?page=T%C3%83%C2%A9l%C3%83%C2%A9chargement ça marche mais pas sur Téléchargement dans le menu, la page proposée est vide...

**Comment by Simounet** [comment]
Corrigé. Merci pour la remarque et désolé pour le temps de réponse. Ça lag un peu par chez nous. :construction:
