### ISSUE TITLE
Meilleure gestion des enclosures

### ISSUE THREAD

**Issue by tmos** [ldleman/Leed#399]
Salut !
J'aimerais proposer une petite modif du comportement de Leed (attendez, partez pas !).

Actuellement les enclosures des flux renvoient automatiquement du html fixe : un div avec un h1, un lien et la description de l'enclosure.
Je pense qu'améliorer la prise en charge de ces éléments et ne pas les considérer comme de simples [cochoneries](https://github.com/ldleman/Leed/blob/f8f268dbb929c96c87c06f9ef7dfa32708a1afea/Feed.class.php#L126) peut ouvrir Leed à de nouveaux horizons, et améliorer grandement l’expérience de certains utilisateurs (amateurs d'images, podcasts, vidéos, etc.).

Donc : est-il possible de passer ça côté affichage ?
L'idée serait de fournir : 
- un **booléen** pour savoir si une enclosure est présente ;
- une façon de connaître son **mime type** (cf [la liste des types wiki](https://en.wikipedia.org/wiki/Mime_type#List_of_common_media_types]), on en distingue que 9 différents).
- et évidement renvoyer aussi **l'url** de l'élément.

À noter que la norme RSS recommande **max 1 enclosure par article**, donc ce n'est pas gênant si Leed n'en n'affiche qu'une :)
L'idée étant évidement que Leed se contente d'offrir un moyen de **détection** et de **typage** des enclosures aux thèmes, et c'est ensuite à eux, s'ils le désirent, de faire une **intégration poussée** (_header imag_é pour chaque article, _player audio_, _vidéo_ etc.). Et accessoirement, si certains sont réfractaires aux enclosures, il suffit de ne pas les implémenter ;)

Dans l'idée, je verrais bien un truc comme ça : 

```
{if="$weHaveEnclosure"}
        {if "enclosureMimeType == audio"}
                <audio src="{enclosureUrl}">
        {elseif …==image}
                <img src="{enclosureUrl}" alt="{enclosureName}">
        {elseif …==video}
                etc.
        {/if}
{/if}
```

Voilà, je pense que ça pourrait être très sympa comme modif, ça permettrait d'avoir des thèmes plus multimédias, plus imagés, et s'adaptant mieux au type d'informations contenus dans les flux, et donc d'améliorer l’expérience de lecture, au lieu de trop la lisser (comme on le reproche souvent aux lecteurs de flux).

**Comment by Simounet** [comment]
Je ne sais pas si @tmos est toujours dans les parages, deux ans après, sait-on jamais. J'ai implémenté cette fonctionnalité dans la PR #429 .
