### ISSUE TITLE
Téléchargement des flux en tâche de fond

### ISSUE THREAD

**Issue by Sbgodin** [ldleman/Leed#401]
Actuellement le téléchargement des flux (_synchronisation_) se fait de façon séquentielle, un flux après l'autre. Si un flux met dix secondes et l'autre met six secondes, ça sera fini dans seize secondes, au lieu de dix si c'était fait en parallèle.
Pour palier ça, le téléchargement est réalisé selon deux modes. Le mode complet télécharge tout, à lancer de temps en temps. Le mode partiel ne synchronise que 10 flux, à lancer plus souvent.

Voici le cheminement de l'idée. Idéalement, on téléchargerait les flux en continu. Pour chaque site, dès que le téléchargement du flux est terminé, on recommence. On ne le fait pas, parce que ça utilise bien trop de bande passante et de ressource processeur pour le bénéfice obtenu. Si on consulte ses flux une fois par jour, à 19h00, autant ne faire qu'un téléchargement complet à 18h55 si ça prend 5 minutes à synchroniser.

Un blog peut mis à jour pourrait n'être sollicité qu'une fois par jour. Un flux d'actualité important pourrait être mis à jour toutes les heures. On pourrait se dire de ne pas rafraîchir la nuit, vu qu'on n'est pas devant l'ordinateur. Non, en fait ! Parce qu'il pourrait y avoir un article intéressant paru la nuit (sites d'un autre fuseau horaire) sur un flux de quelques articles seulement. Dans ce cas, l'article intéressant apparaît en début de nuit et disparaît au matin ; il ne sera pas lu par les autres. C'est sûrement le cas de _Google News_ édition U.S....

Donc on précise pour chaque flux la fréquence d'actualisation souhaitée. Mais aussi par heure ! En effet, par hypothèse je ne veux rien rater de _Google News US_. Mais le petit blog hébergé sur un petit ordinateur, mis à jour une fois par semaine avec une taille de flux équivalente à plusieurs mois d'articles peut attendre la mise à jour journalière !
Donc, par article, une densité de probabilité de mise à jour sur une journée, voire sur une semaine. À chaque instant, on sait quelle est la probabilité qu'un téléchargement d'un flux est fait.

De l'autre côté, il y a la ressource. Ce qui vient d'être écrit concerne le flux sortant des flux auxquels on est abonné. Mais il faut aussi gérer la bande passante du serveur ! Sinon, à 19h00 encore, on risque de télécharger 1000 flux (par exemple) sans abîmer les serveurs en face, mais en mettant à genoux le notre.
Il faut donc limiter la bande passante et le débit instantané côté serveur, et pouvoir déterminer si le scénario de téléchargement est compatible avec la bande passante et le débit. Si ce n'est pas le cas, alors il faudra délester en renonçant à télécharger certains flux.

En fait, il faut aussi prendre en compte le cas d'un utilisateur mettant à jour le flux manuellement. De même s'il y a plusieurs utilisateurs, il ne faudra pas déclencher de suite un téléchargement mais enregistrer la demande...

L'architecture serait donc comme suit : un gestionnaire réseau tourne à tout moment en tâche de fond (ou lancé toutes les secondes, voire minutes). Un gestionnaire de file d'attente chargé d'enregistrer les nouvelles requêtes, de détecter les doublons, etc. Un gestionnaire programmateur qui enregistre les demandes en provenance de l'utilisateur ou de la configuration.

Techniquement, on peut déjà commencer par lancer des téléchargements asynchrones avec Php. La bibliothèque Curl permet de le faire. Voir [php.net](http://php.net/manual/fr/book.curl.php/) les fonctions "curl_multi_*".
Un exemple d'utilisation est donné par [Timo](http://lehollandaisvolant.net/index.php?d=2014/05/20/19/21/36-php-faire-plusieurs-requetes-http-simultanees-avec-curl).

**Comment by Simounet** [comment]
Je ferme car j'ai créé et j'utilise depuis un moment un plugin permettant la gestion intelligente des mises à jour en fonction de la fréquence de publications : https://github.com/Leed-market/LeedSmartFeedsUpdate .
