### ISSUE TITLE
Decompte negatif

### ISSUE THREAD

**Issue by ldleman** [ldleman/Leed#404]
> Reporté par mail par Leo
> Bonjour,

Je suis un utilisateur enthousiaste de leed et je tiens à vous remercier ainsi que tous les contributeurs.

Il me semble avoir trouvé un petit bug dans la version de leed que j'ai installé il y a quelques jours (j'ai joint l'archive au courriel).
En effet, sur la page d'accueil, lorsque tous les articles ont été lus et qu'aucun n'est affiché, si l'on utilise le raccourcis pour marquer un article comme lus (la touche  m), la valeur affiché en parenthèses après "Non lus" devient négative.
Je joint également une capture d'écran pour illustrer mon propos.

Je ne possède pas de compte sur Github, c'est pourquoi je me permets de vous signaler ceci par courriel.

Cordialement
Léo

**Comment by Sbgodin** [comment]
Je ferme. Rouvrir si nécessaire.
