### ISSUE TITLE
champs TEXT

### ISSUE THREAD

**Issue by kraoc** [ldleman/Leed#406]
Je viens de commencer un 'petit audit' sur mes tables Leed et la première chose qui viens de me causer une fracture occulaire c'est l'utilisation des champs pour la clée de la table configuration.
Sur mon installation, la longeur max [SELECT max(length(`key`)) FROM leed_configuration] est de 27 caractères...

Soit je me suis trompé, ce qui est possible; soit un petit VARCHAR(50) permettrait de gagner en espace de stockage et de poser un index... 

Me trompes-je :) ???

**Comment by Sbgodin** [comment]
La configuration est lue une fois par session, ensuite elle n'est plus relue. Un rechargement de page, dans la même session, ne nécessite pas une relecture de cette table. La performance de lecture peut être un peu sacrifiée au regard de la facilité d'écriture.
