### ISSUE TITLE
Reverse Proxy : Cookies Path

### ISSUE THREAD

**Issue by FanchTheSystem** [ldleman/Leed#413]
Bonjour et merci pour leed ;)

La connection à Leed à travers un reverse proxy est impossible a cause d'un probleme de path pour les cookies.

J'ai configuré mon proxy pour que "leed.mondomaine.org" pointe vers un serveur local du genre "http://localhost/leed". 

Du coup le path du cookie defini par mon instance leed contient /leed, a cause de common.php, Ligne 34 :  
```php
if(dirname($_SERVER['SCRIPT_NAME'])!='/') $cookiedir=dirname($_SERVER["SCRIPT_NAME"]).'/';
```

Le resultat est que la connexion à mon instance est impossible :(

J'ai donc commenté cette ligne chez moi, et ca marche maintenant sans souci.

Peut-etre que ce chemin pourrai etre ecrasé par une variable dans constant.php ? Ou alors utiliser les variables HTTP_X_FORWARDED* pour detecter tout ca automatiquement.

**Comment by Sbgodin** [comment]
Ceci avait été rajouté (dc55b826979e21db4ff9a4000ba64089326255e3) pour corriger (#254). Faute de solution évidente, je ne pense pas souhaitable de se passer de cette ligne.
