### ISSUE TITLE
Support de PubSubHubbub

### ISSUE THREAD

**Issue by julien51** [ldleman/Leed#414]
En regardant qui faisait du polling sur notre flux RSS, j'ai trouvé une install de Leed! 

[PubSubHubbub](https://code.google.com/p/pubsubhubbub/) est un protocol ouvert (créée par Google) qui permet aux lecteurs tels que Kriss de recevoir des pings quand un flux est mis à jour... cela permete de reduire la fréquence de polling tout en propageant les données de ces flux en temps réel. C'est implémenté par Feedly, Newsblur, Feedbin... etc.

Si vous souhiatez l'implémenter, j'ai écris un petit [tutoriel](http://blog.superfeedr.com/howto-pubsubhubbub/).

**Comment by Simounet** [comment]
Bonjour Julien,
J'avais regardé cette techno très intéressante il y a quelques années et j'avais été séduit. Concernant Leed, c'est une bonne idée mais pas vraiment dans les priorités vu le nombre de sites assez réduit qui l'imprémente (surtout en France).

**Comment by julien51** [comment]
@Simounet ha! Il y a quand meme OverBlog, Blogger, Wordpress, Medium, Feedburner... etc; Ca devrrait faire du monde, nom?

**Comment by Simounet** [comment]
J'ai regardé sur quelques blogs tech fr connus et sans succès. J'ai enchaîné avec les sites de news fr (style le Monde ou l'Equipe) qui publient des dizaines de news par jour, sans succès non plus. Les plate-formes que tu as cité l'intègrent-elles par défaut ? Je n'ai pas l'impression que ce soit le cas de WordPress par exemple.

**Comment by julien51** [comment]
Oui, par defaut sur tous les wordpress.com et pour les .org, il y a
plusieurs plugins qui l'intègrent.
Pour ce qui est des gros "publishers" media, en général, c'est vrai que
c'est pas folichon car ils utilisent pour la plupart de vieux CMS.

**Comment by Simounet** [comment]
Je n'ai pas réussi à en trouver sur les wordpress.com. Sur les auto-hébergés, il existe bien des plugins mais rien par défaut. Je ne conteste pas l'intérêt de la techno, c'est juste que son utilisation me semble marginale.
J'ai tout de même envie de l'ajouter à Leed, ça peut toujours être utile et c'est vrai qu'au niveau des perfs, tout le monde est gagnant en évitant un tas de requêtes inutiles.

**Comment by julien51** [comment]
Heu, tu as regardé quel wp.com? Parce que tous ceux que je regarde ont:
`<atom:link rel='hub' href='https://xxxx.wordpress.com/?pushpress=hub'/>` 
avec xxxx qui est le nom du blog. Par exemple: https://matt.wordpress.com/

**Comment by Simounet** [comment]
Oops, je cherchais "hub". Bien cool tout ça et si tu veux l'implémenter sur Leed, n'hésite pas. ;)
