### ISSUE TITLE
Logger les echecs de connexions

### ISSUE THREAD

**Issue by dbeniamine** [ldleman/Leed#416]
Bonjour,

J'utilise leed (version multi-user) depuis plusieurs années, et je me rends compte
que les erreurs  de connexions ne sont pas loggé, ce qui empêche de mettre en
place une protection contre des attaques de type brute force (fail2ban par exemple).

J'ai modifié le fichier action.php pour mettre en place un tel log:

```
diff --git a/action.php b/action.php
index 7e0c55a..37992db 100755
--- a/action.php
+++ b/action.php
@@ -449,6 +449,7 @@ switch ($action){
        if(isset($_['usr'])){
            $user = $userManager->existAuthToken($_['usr']);
            if($user==false){
+                error_log("user ".$_['usr']." authentication failure");
                exit("erreur identification : le compte est inexistant");
            }else{
                $_SESSION['currentUser'] = serialize($user);
@@ -457,6 +458,7 @@ switch ($action){
        }else{
                $user = $userManager->exist($_['login'],$_['password']);
            if($user==false){
+                error_log("user ".$_['login']." authentication failure");
                exit("erreur identification : le compte est inexistant");
            }else{
                $_SESSION['currentUser'] = serialize($user);
```

Cordialement,
David

**Comment by Sbgodin** [comment]
Je note (tardivement) l'idée. Je verrai à l'occasion. De ton côté, n'hésite pas à faire des requêtes de fusion.

Merci pour la proposition.

**Comment by Sbgodin** [comment]
Je n'ai mit le message que dans un cas. L'autre cas (existAuthToken) ne fait pas appel au mot de passe.
