### ISSUE TITLE
Valeur par défaut de Pubdate

### ISSUE THREAD

**Issue by Tabrisange** [ldleman/Leed#417]
Dans la base de leed, j'ai remarqué dans la table de leed_event que  certains flux qui n'ont pas de date dans le rss, ont un timestamp unix par défaut :
"1970-01-01 01:00:00"

Or il serait bien de mettre une valeur par défaut lors de l'insertion, qui soit la date au moment de la mise à jour

**Comment by Sbgodin** [comment]
Pour être sûr que nous parlons de la même chose, il s'agit bien des _pubdate_ qui sont à zéro ?

**Comment by Tabrisange** [comment]
Oui ou bien de certains situés dans le futur.
Oui j'ai eu le cas de certains pubdate qui étaient dans le futur ^^

**Comment by Simounet** [comment]
Il me semble que celles dans le futur ne sont pas problématiques, si ?

**Comment by Tabrisange** [comment]
problématiques, pas vraiment mais gênantes car ça reste en haut des  non lu

**Comment by Simounet** [comment]
Je comprends mais c'est parfois désiré. J'ai par exemple un flux qui m'annonce la date de sortie des albums d'artistes que j'apprécie.

**Comment by Sbgodin** [comment]
Pour ma part, mettre le pubdate à la date de mise à jour ne me rebute pas. Voyez-vous des obstacles à ce qu'on le fasse ?

Si pubdate==0 alors pubdate=={dateMiseÀJour}

**Comment by Simounet** [comment]
Pour ce cas là, aucun problème.
