### ISSUE TITLE
Extension php mysql deprecated

### ISSUE THREAD

**Issue by Tabrisange** [ldleman/Leed#418]
Bonjour,
l'extension mysql de phph est deprecated et il est indiqué qu'il vaut mieux utiliser mysqli ou pdo.

Vu le peu d'activité en ce moment, le passage à mysqli est-il prévu ? Et si oui quand ?

**Comment by BurakDev** [comment]
UP

**Comment by Spyneur** [comment]
Salut,

Comme j'ai eu le problème assez récemment m'empêchant de ré-installer Leed, cela te pose t-il problème lors de l'installation ?

Si tel est le cas, un simple " apt-get install php5-mysql " suffit à régler le problème en attendant un passage à mysqli.

Voila voila ;)

**Comment by Tabrisange** [comment]
Je ne vois pas en quoi le fait que l'extension soit deprecated empêche de l'utiliser.
Je dis juste que le fait qu'elle soit deprecated à partir de php5 pose justement problème et qu'il vaudrait mieux la changer par mysqli ou bien pdo

**Comment by Spyneur** [comment]
Ah j'ai mal compris dans ce cas, désolé ^^'

**Comment by Simounet** [comment]
Coucou les gens,
Vu que l'extension mysql sera purement et simplement supprimée dans PHP 7, je me suis mis au boulot : https://github.com/Simounet/Leed/commit/e67327a2ca487dd6b7704eb475c817efe2fdb6ee . Vous pouvez tester ça et me dire si vous avez des soucis particuliers.

**Comment by cobalt74** [comment]
Salut cool merci. Je suis en train de me remettre au code. Mais j'ai subi le début de l'hiver précoce... Dur dur. Fait moi signe pour les tests

**Comment by Simounet** [comment]
Salut @cobalt74 , ça faisait longtemps. Comme j'ai dit dans mon précédent message, tout est dispo sur mon repo. J'ai tout mis sur la master donc tu peux tester là si ça te dit.

**Comment by BurakDev** [comment]
A vu d'oeil tout à l'air correct, je te donnerais un feedback quand j'aurais bien testé

**Comment by Simounet** [comment]
Réglé par le commit 1836b28dc881e437eff091d41b8f2b68b01f9c7e.
