### ISSUE TITLE
Dernière mise à jour: cron impossible

### ISSUE THREAD

**Issue by kraoc** [ldleman/Leed#420]
J'ai mis la dernière version sur mon hébergement.
J'ai une tache cron sur une autre machine qui tombe en erreur avec le script de mise à jour m'indiquant qu'il faut être identifié...
Comment puis-je la résoudre ?

**Comment by Sbgodin** [comment]
Hello :-)

Histoire de pouvoir reproduire ça de mon côté, peux-tu m'indiquer :
* la commande exécutée par cron,
* la sortie envoyée par cron,
* la commande ainsi que sa sortie quand tu la lances à la main.

**Comment by kraoc** [comment]
Hello :)

*La commande exécuté par cron:*
wget --inet4-only --no-check-certificate -O /tmp/leed.olivier.dat http://cybride.net/rss/synchronize/olivier

*La sortie:*
`--2016-01-02 15:41:20--  http://cybride.net/rss/synchronize/olivier
Résolution de cybride.net (cybride.net)… 104.28.27.80, 104.28.26.80
Connexion à cybride.net (cybride.net)|104.28.27.80|:80… connecté.
requête HTTP transmise, en attente de la réponse… 403 Forbidden
2016-01-02 15:41:20 erreur 403 : Forbidden.`

# Si je passe par cURL:

*La commande:*
curl http://cybride.net/rss/synchronize/olivier

*La sortie:*
`<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
<script type="text/javascript">
//<![CDATA[
try{if (!window.CloudFlare) {var CloudFlare=[{verbose:0,p:1451684194,byc:0,owlid:"cf",bag2:1,mirage2:0,oracle:0,paths:{cloudflare:"/cdn-cgi/nexp/dok3v=1613a3a185/"},atok:"7c70da437f2ef4bc619487e8e8442c0a",petok:"1ef7086001c350f55603f3af27889303b24de1de-1451745770-1800",zone:"cybride.net",rocket:"0",apps:{"abetterbrowser":{"config":"none"}},sha2test:0}];!function(a,b){a=document.createElement("script"),b=document.getElementsByTagName("script")[0],a.async=!0,a.src="//ajax.cloudflare.com/cdn-cgi/nexp/dok3v=38857570ac/cloudflare.min.js",b.parentNode.insertBefore(a,b)}()}}catch(e){};
//]]>
</script>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access /rss/synchronize/olivier
on this server.</p>
</body></html>
`

**Comment by kraoc** [comment]
Si je passe par la mise à jour sous Leed ça fonctionne parfaitement...

**Comment by Sbgodin** [comment]
J'avais modifié ça il y a bien longtemps. Souvenirs ^^ Le [README](https://github.com/ldleman/Leed/blob/master/README.md) est à jour et il y a deux façons de faire la mise à jour. En résumé, 

    cd (...)/leed && php action.php >> logs/cron.log 2>&1

    wget --no-check-certificate --quiet --output-document /var/www/leed/cron.log \
    "http://127.0.0.1/leed/action.php?action=synchronize&code=votre_code_synchronisation"

L'appel en ligne de commande (et dans le cron) est à préférer. Comme c'est local, pas besoin de montrer patte blanche. La deuxième façon, _wget_, peut être appelée localement mais aussi à distance. Et là, il faut montrer patte blanche en fournissant le code de synchronisation. Ce code est disponible dans les préférences de _Leed_.

Bonne année :-)

**Comment by kraoc** [comment]
Je viens de mettre à jour mon script cron et ça fonctionne.
En revanche j'utilisais une règle de redirection par htaccess et ça ne passe pas.
En mettant directement la bonne url ça fonctionne... c'est étrange mais le résultat me convient !

Merci beaucoup :)

Et bonne année ^^
