### ISSUE TITLE
Fatal error: Uncaught exception 'RainTpl_NotFoundException'

### ISSUE THREAD

**Issue by gCyrille** [ldleman/Leed#421]
Bonjour à tous,
D'abord merci pour Leed que vous développez et maintenez :)

J'ai fait hier une mise à jour de mon installation de Leed et j'ai depuis une erreur.
Au départ j'ai fait la mise à jour via le plugin, mais ayant l'erreur j'ai refais une mise à jour manuellement, sans plus succès.

J'ai alors tout nettoyé, refait une installation mais remit le "constant.php" d'origine. Tout fonctionnait bien, jusqu'à ce que l'erreur réapparaisse ce matin.

Voici le message d'erreur :
    
    Fatal error: Uncaught exception 'RainTpl_NotFoundException' with message 'Template index not found!' in /home/cyrilleg/www-leed/RainTPL.php:271 Stack trace: #0 /home/cyrilleg/www-leed/RainTPL.php(164): RainTPL->check_template('index') #1 /home/cyrilleg/www-leed/footer.php(4): RainTPL->draw('index') #2 /home/cyrilleg/www-leed/index.php(157): require_once('/home/cyrilleg/...') #3 {main} thrown in /home/cyrilleg/www-leed/RainTPL.php on line 271

J'ai un hébergement ovh perso, et jusqu'à maintenant tout fonctionnait bien.
Ai-je raté une manipulation lors de la mise à jour ?

Merci d'avance de votre aide :)

**Comment by cobalt74** [comment]
Hello. Tu utilises le thème par défaut ?

**Comment by gCyrille** [comment]
Bonjour,
J'utilise bien le thème par défaut. J'ai bien vérifié lorsque j'ai fait la manip de réinstallation que c'était bien le thème par défaut de sélectionné. (Sinon y a t-il un moyen de vérifier directement dans la base de données ?)

**Comment by Sbgodin** [comment]
Vers quelle version as-tu mis à jour ? Idéalement, il faudrait la révision exacte.

**Comment by gCyrille** [comment]
Ha oui en effet c'est mieux de préciser, désolé:
J'ai mis à jour vers la dernière version stable, ed271fb3b47669f225d5ed8aa7160359dc5cb08e

En revanche je ne sais absolument pas de quelle version je suis parti (sur le coup je n'ai pas pensé au fait que ça puisse planter... erreur de débutant je n'ai même pas fait de backup...).

**Comment by cobalt74** [comment]
dans la table configuration de leed, tu as le theme et quelques informations importantes.
A voir si cela ne vient pas de là.
Pour le test, construit toi une instance propre afin de s'assurer que la version téléchargée fonctionne correctement sur ton hébergement sans avoir un historique qui probablement génère le soucis.
Tu utilises une base de données déjà existante donc il est possible que certaines requetes de MAJ ne soit pas passé correctement, tu les trouves dansle répertoire update. 
Vérifie aussi les droits des répertoires et fichiers sur ton serveur.

**Comment by gCyrille** [comment]
J'ai vérifié la table de configuration et comparé avec une nouvelle instance et elle semble assez différente (entre autre le champ "theme" qui n'est pas présent dans l'ancien...)
C'est probablement les requêtes de MAJ qui ne sont pas passée correctement.
J'ai donc procédé à une nouvelle installation et une migration manuelle via sql de mes feed et folder.
Pour le moment je n'ai plus d'erreur mais comme précédemment c'était apparu après un certain temps je reste vigilant.

Merci pour les conseils.

Cyrille.

**Comment by cobalt74** [comment]
De rien Cyrille. J'espère que tu retrouvera tout tes petits ;)
Bonne soirée. :+1:

**Comment by Simounet** [comment]
Plus d'un mois sans nouvelle. Je vais prendre ça comme une résolution. Je ferme. :8ball:
