### ISSUE TITLE
[suggestion] Changement du champ guid

### ISSUE THREAD

**Issue by Tabrisange** [ldleman/Leed#430]
Bonjour.

J'ai remarqué que le champ guid  quand il n'existe pas dans le flux est l'url  du post.
Cependant la colonne guid elle même est de type mediumtext
Ne vaudrait-il pas mieux la mettre en varchar(255) ?

Sachant que selon la doc mysql : 
MEDIUMTEXT [CHARACTER SET charset_name] [COLLATE collation_name]

A TEXT column with a maximum length of 16,777,215 (224 − 1) characters. The effective maximum length is less if the value contains multibyte characters. Each MEDIUMTEXT value is stored using a 3-byte length prefix that indicates the number of bytes in the value. 

Je pense que pour un guid unique nous n'avons pas besoin d'une telle longueur de caractères

De plus dans le cas d'une url, ne pourrait-on pas la transformer en hash, sha256 par exemple  pour éviter les collisions ?

Ainsi la longueur serait moindre et plus facile à indexer

Cordialement

Florianne

**Comment by Sbgodin** [comment]
À mon humble avis, le varchar(255) n'est pas adapté à une information de taille arbitraire. Par contre, l'idée du condensat (sha256) est chouette, même s'il y a un très petit risque de collision. Bon, on pourrait faire une table de hachage...

En fait, je pense que le champ doit pouvoir être de taille arbitraire et doit rester lisible. La lisibilité est nécessaire pour des requêtes futures sur le contenu du flux. La taille arbitraire permet de pallier à tout soucis d'implémentation, de changement de spécifications des flux, etc.

Donc, je suppose que le champ _guid_ est bien tel quel.

**Comment by Tabrisange** [comment]
Je ne suis pas d'accord car la taille de la colonne est beaucoup trop important par rapport à son usage, un simple type TEXT suffirait : 

TEXT[(M)] [CHARACTER SET charset_name] [COLLATE collation_name]

A TEXT column with a maximum length of 65,535 (216 − 1) characters. The effective maximum length is less if the value contains multibyte characters. Each TEXT value is stored using a 2-byte length prefix that indicates the number of bytes in the value.

An optional length M can be given for this type. If this is done, MySQL creates the column as the smallest TEXT type large enough to hold values M characters long.

**Comment by Sbgodin** [comment]
Chez moi, j'ai ça :
> mysql> desc event;
+-------------+------------------+------+-----+---------+----------------+
| Field       | Type             | Null | Key | Default | Extra          |
+-------------+------------------+------+-----+---------+----------------+
(...)
| guid        | text             | NO   | MUL | NULL    |                |
(...)+-------------+------------------+------+-----+---------+----------------+

Donc _guid_ est déjà de type TEXT. Sachant que la différence entre les 3 types est le nombre d'octet de l'en-tête indiquant la longueur du champ.

**Comment by Tabrisange** [comment]
Moi j'ai ça : 

+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| leed_event | CREATE TABLE `leed_event` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `guid` mediumtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `title` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `creator` varchar(225) COLLATE utf8mb4_unicode_ci NOT NULL,
  `content` mediumtext COLLATE utf8mb4_unicode_ci,
  `description` mediumtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `link` mediumtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `unread` int(11) NOT NULL,
  `feed` int(11) NOT NULL,
  `favorite` int(11) NOT NULL,
  `pubdate` int(11) NOT NULL,
  `syncId` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `indexfeed` (`feed`),
  KEY `indexunread` (`unread`),
  KEY `indexfavorite` (`favorite`),
  KEY `dba_idx_leed_event_1` (`guid`(20),`feed`),
  KEY `dba_idx_leed_event_2` (`feed`,`guid`(20)),
  KEY `dba_idx_leed_event_3` (`feed`,`unread`),
  KEY `dba_idx_leed_event_4` (`pubdate`),
  KEY `dba_idx_leed_event_5` (`guid`(60),`feed`)
) ENGINE=InnoDB AUTO_INCREMENT=515191 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC |


bizarre

**Comment by Sbgodin** [comment]
Leed crée ses tables via les classes dédiées. Dans le fichier [MysqlEntity.php](https://github.com/ldleman/Leed/blob/508e44e9e2021a693de703934da9818c945182a8/MysqlEntity.class.php#L29) il y a la traduction des types de Leed vers Mysql. Pour _longstring_ on trouve _TEXT_. Ensuite dans [Event.class.php](https://github.com/ldleman/Leed/blob/1836b28dc881e437eff091d41b8f2b68b01f9c7e/Event.class.php#L17) la structure de la table indique _longstring_ pour _guid_. Donc _TEXT_ pour _guid_.

**Comment by Tabrisange** [comment]
Je viens de vérifier, j'ai la même chose dans les deux fichiers.
Mais je n'ai jamais modifié ça moi :o

**Comment by Sbgodin** [comment]
Du coup, le type de _guid_ est convenable. On peut fermer ce ticket ?
