### ISSUE TITLE
Code mort possible sur gestion des greffons

### ISSUE THREAD

**Issue by Sbgodin** [ldleman/Leed#447]
J'ai repéré des sections non traduites dans _marigolds/js/script.js_, fonction _jsonp_. Mais cette fonction _jsonp_ n'est pas utilisée ailleurs, sauf dans le source de jquery...

C'est peut-être du code mort, auquel cas il faut y faire le ménage. Quelqu'un pour confirmer ?

**Comment by Simounet** [comment]
Je pense effectivement que c'est du code mort qui a dû servir à l'ancienne gestion du market (837fe6c) même si je ne trouve aucune réelle trace d'utilisation.
