### ISSUE TITLE
Maintenance de Marigolds-old

### ISSUE THREAD

**Issue by Sbgodin** [ldleman/Leed#451]
Hello tous,

Est-il encore utile de maintenir le thème _Marigolds-old_ ? Tous les développements (OTP, etc.) doivent y être répliqués, ce qui ajoute une charge à chaque modification.

Je souhaite que nous supprimions ce thème, l'actuel _Marigolds_ fonctionnant comme attendu.

@tmos, maintiens-tu encore [Greeder](https://github.com/tmos/greeder) ?

**Comment by Simounet** [comment]
Décidemment, tu lis dans mes pensées aujourd'hui. Le boulot que je fais pour le multi-utilisateurs ne prend pas en compte cet ancien thème et je pense que sa valeur ajoutée est trop faible.

**Comment by Sbgodin** [comment]
Alors j'attends encore un peu, pour que @ldleman se manifeste, et on souhaitera bon vent à ce vénérable thème.

**Comment by tmos** [comment]
Greeder est bel et bien arrêté, en tout cas de mon côté !

**Comment by ldleman** [comment]
pas de soucis pour moi, le nouveaux thème marigold remplit sa fonction bien qu'il mériterais un petit coup de polish histoire de s'adapter aux tendance ui actuelles.

**Comment by Sbgodin** [comment]
C'est fait. RIP Marigolds (old).

**Comment by Simounet** [comment]
Marig-old-s ? Ok, je suis déjà sorti. :D

**Comment by ldleman** [comment]
PAN !!
